apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/newbare/homelab-gitops.git
    targetRevision: main
    path: infrastructure/observability
    directory:
      include: "jaeger-cr.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  ignoreDifferences:
    - group: jaegertracing.io
      kind: Jaeger
      jsonPointers:
        - /spec
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
