apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/newbare/homelab-gitops.git
    targetRevision: main
    path: infrastructure/observability
    directory:
      include: "kiali-cr.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
