// This file is auto-generated by backstage-cli translations import
// Do not edit manually.

import { createTranslationResource } from '@backstage/frontend-plugin-api';
import { apiDocsTranslationRef } from '@backstage/plugin-api-docs/alpha';
import { catalogTranslationRef } from '@backstage/plugin-catalog/alpha';
import { catalogGraphTranslationRef } from '@backstage/plugin-catalog-graph/alpha';
import { catalogImportTranslationRef } from '@backstage/plugin-catalog-import/alpha';
import { catalogReactTranslationRef } from '@backstage/plugin-catalog-react/alpha';
import { coreComponentsTranslationRef } from '@backstage/core-components/alpha';
import { homeTranslationRef } from '@backstage/plugin-home/alpha';
import { homeReactTranslationRef } from '@backstage/plugin-home-react/alpha';
import { kubernetesTranslationRef } from '@backstage/plugin-kubernetes/alpha';
import { kubernetesReactTranslationRef } from '@backstage/plugin-kubernetes-react/alpha';
import { orgTranslationRef } from '@backstage/plugin-org/alpha';
import { notificationsTranslationRef } from '@backstage/plugin-notifications/alpha';
import { scaffolderTranslationRef } from '@backstage/plugin-scaffolder/alpha';
import { scaffolderReactTranslationRef } from '@backstage/plugin-scaffolder-react/alpha';
import { searchTranslationRef } from '@backstage/plugin-search/alpha';
import { searchReactTranslationRef } from '@backstage/plugin-search-react/alpha';
import { techdocsTranslationRef } from '@backstage/plugin-techdocs/alpha';
import { userSettingsTranslationRef } from '@backstage/plugin-user-settings/alpha';

export default [
  createTranslationResource({
    ref: apiDocsTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/api-docs.pt.json'),
    },
  }),
  createTranslationResource({
    ref: catalogTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/catalog.pt.json'),
    },
  }),
  createTranslationResource({
    ref: catalogGraphTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/catalog-graph.pt.json'),
    },
  }),
  createTranslationResource({
    ref: catalogImportTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/catalog-import.pt.json'),
    },
  }),
  createTranslationResource({
    ref: catalogReactTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/catalog-react.pt.json'),
    },
  }),
  createTranslationResource({
    ref: coreComponentsTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/core-components.pt.json'),
    },
  }),
  createTranslationResource({
    ref: homeTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/home.pt.json'),
    },
  }),
  createTranslationResource({
    ref: homeReactTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/home-react.pt.json'),
    },
  }),
  createTranslationResource({
    ref: kubernetesTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/kubernetes.pt.json'),
    },
  }),
  createTranslationResource({
    ref: kubernetesReactTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/kubernetes-react.pt.json'),
    },
  }),
  createTranslationResource({
    ref: orgTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/org.pt.json'),
    },
  }),
  createTranslationResource({
    ref: notificationsTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/plugin.notifications.pt.json'),
    },
  }),
  createTranslationResource({
    ref: scaffolderTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/scaffolder.pt.json'),
    },
  }),
  createTranslationResource({
    ref: scaffolderReactTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/scaffolder-react.pt.json'),
    },
  }),
  createTranslationResource({
    ref: searchTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/search.pt.json'),
    },
  }),
  createTranslationResource({
    ref: searchReactTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/search-react.pt.json'),
    },
  }),
  createTranslationResource({
    ref: techdocsTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/techdocs.pt.json'),
    },
  }),
  createTranslationResource({
    ref: userSettingsTranslationRef,
    translations: {
    "pt": () => import('./../../translations/messages/user-settings.pt.json'),
    },
  }),
];
