apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/newbare/homelab-gitops.git
    targetRevision: main
    path: infrastructure/backstage
    directory:
      include: "ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
